'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.5472
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class DrRegist

    '''<summary>
    '''BtnCancel コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ImgCanceled コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ImgCanceled As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Tr1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Tr1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''KOUENKAI_NO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KOUENKAI_NO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KOUENKAI_FROM_DATE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KOUENKAI_FROM_DATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KOUENKAI_TO_DATE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KOUENKAI_TO_DATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Tr2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Tr2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''KOUENKAI_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KOUENKAI_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TAXI_PRT_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TAXI_PRT_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KIKAKU_TANTO_JIGYOBU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIKAKU_TANTO_JIGYOBU As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KIKAKU_TANTO_AREA コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIKAKU_TANTO_AREA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KIKAKU_TANTO_EIGYOSHO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIKAKU_TANTO_EIGYOSHO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KIKAKU_TANTO_NO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIKAKU_TANTO_NO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KIKAKU_TANTO_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIKAKU_TANTO_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KIKAKU_TANTO_KEITAI コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIKAKU_TANTO_KEITAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KIKAKU_TANTO_EMAIL コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIKAKU_TANTO_EMAIL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TEHAI_TANTO_JIGYOBU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TEHAI_TANTO_JIGYOBU As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TEHAI_TANTO_AREA コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TEHAI_TANTO_AREA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TEHAI_TANTO_EIGYOSHO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TEHAI_TANTO_EIGYOSHO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TEHAI_TANTO_NO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TEHAI_TANTO_NO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TEHAI_TANTO_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TEHAI_TANTO_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TEHAI_TANTO_KEITAI コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TEHAI_TANTO_KEITAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TEHAI_TANTO_EMAIL コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TEHAI_TANTO_EMAIL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label5 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label6 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label7 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MR_SEND_SAKI_FS コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents MR_SEND_SAKI_FS As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MR_SEND_SAKI_OTHER コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents MR_SEND_SAKI_OTHER As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DR_MPID コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DR_MPID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DR_CD コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DR_CD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UPDATE_DATE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UPDATE_DATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''STATUS_TEHAI コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents STATUS_TEHAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DR_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DR_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TblMust コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblMust As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''DR_NAME_FIRST コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DR_NAME_FIRST As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DR_NAME_LAST コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DR_NAME_LAST As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DR_NAME_KANA_FIRST コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DR_NAME_KANA_FIRST As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DR_NAME_KANA_LAST コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DR_NAME_KANA_LAST As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SEX_Male コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SEX_Male As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''SEX_Female コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SEX_Female As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''PREFECTURES_NO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents PREFECTURES_NO As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SHISETSU_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SHISETSU_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SHISETSU_NAME_KANA コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SHISETSU_NAME_KANA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''KAMOKU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KAMOKU As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''YAKUSHOKU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents YAKUSHOKU As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AGE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents AGE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PUBLIC_SERVANT_Yes コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents PUBLIC_SERVANT_Yes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''PUBLIC_SERVANT_No コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents PUBLIC_SERVANT_No As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''SECANDARY_USE_Yes コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SECANDARY_USE_Yes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''SECANDARY_USE_No コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SECANDARY_USE_No As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''TrTEHAI_HOTEL_0 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrTEHAI_HOTEL_0 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TdTEHAI_HOTEL_0 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdTEHAI_HOTEL_0 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TEHAI_HOTEL_Yes コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TEHAI_HOTEL_Yes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''TEHAI_HOTEL_No コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TEHAI_HOTEL_No As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''TrTEHAI_HOTEL_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrTEHAI_HOTEL_1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TdTEHAI_HOTEL_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdTEHAI_HOTEL_1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''CHECK_IN コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents CHECK_IN As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CHECK_OUT コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents CHECK_OUT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TrTEHAI_HOTEL_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrTEHAI_HOTEL_2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TdTEHAI_HOTEL_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdTEHAI_HOTEL_2 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''HOTEL_SMOKING_No コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HOTEL_SMOKING_No As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''HOTEL_SMOKING_Yes コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HOTEL_SMOKING_Yes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''TrTEHAI_HOTEL_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrTEHAI_HOTEL_3 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TdTEHAI_HOTEL_5 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdTEHAI_HOTEL_5 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''NOTE_HOTEL コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents NOTE_HOTEL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TrTEHAI_HOTEL_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrTEHAI_HOTEL_4 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TdTEHAI_HOTEL_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdTEHAI_HOTEL_3 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ACCOMPANY_FLAG_Yes コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ACCOMPANY_FLAG_Yes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''ACCOMPANY_FLAG_No コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ACCOMPANY_FLAG_No As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''TrTEHAI_HOTEL_5 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrTEHAI_HOTEL_5 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TdTEHAI_HOTEL_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdTEHAI_HOTEL_4 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ACCOMPANY_STAY_Yes コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ACCOMPANY_STAY_Yes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''ACCOMPANY_STAY_No コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ACCOMPANY_STAY_No As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Image2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Image2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HyperLink1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HyperLink1 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''DivACCOMPANY コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DivACCOMPANY As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ACCOMPANY_STAY_DATE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ACCOMPANY_STAY_DATE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ACCOMPANY_SAME_ROOM コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ACCOMPANY_SAME_ROOM As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''TblACCOMPANY コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblACCOMPANY As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''ACCOMPANY_ADULT_SU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ACCOMPANY_ADULT_SU As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ACCOMPANY_CHILD_SU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ACCOMPANY_CHILD_SU As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TblACCOMPANY_CHILD コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblACCOMPANY_CHILD As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''TrACCOMPANY_CHILD_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrACCOMPANY_CHILD_1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ACCOMPANY_CHILD_AGE_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ACCOMPANY_CHILD_AGE_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ACCOMPANY_CHILD_SEX_1_Male コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ACCOMPANY_CHILD_SEX_1_Male As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''ACCOMPANY_CHILD_SEX_1_Female コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ACCOMPANY_CHILD_SEX_1_Female As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''ACCOMPANY_CHILD_BED_1_Yes コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ACCOMPANY_CHILD_BED_1_Yes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''ACCOMPANY_CHILD_BED_1_No コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ACCOMPANY_CHILD_BED_1_No As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''TrACCOMPANY_CHILD_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrACCOMPANY_CHILD_2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ACCOMPANY_CHILD_AGE_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ACCOMPANY_CHILD_AGE_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ACCOMPANY_CHILD_SEX_2_Male コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ACCOMPANY_CHILD_SEX_2_Male As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''ACCOMPANY_CHILD_SEX_2_Female コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ACCOMPANY_CHILD_SEX_2_Female As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''ACCOMPANY_CHILD_BED_2_Yes コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ACCOMPANY_CHILD_BED_2_Yes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''ACCOMPANY_CHILD_BED_2_No コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ACCOMPANY_CHILD_BED_2_No As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''NOTE_ACCOMPANY コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents NOTE_ACCOMPANY As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TrSANKA_KUBUN コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrSANKA_KUBUN As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''SANKA_KUBUN_Listener コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SANKA_KUBUN_Listener As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''SANKA_KUBUN_Speaker コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SANKA_KUBUN_Speaker As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''PARTY_Yes コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents PARTY_Yes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''PARTY_No コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents PARTY_No As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''BYCAR_Yes コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BYCAR_Yes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''BYCAR_No コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BYCAR_No As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''TrTEHAI_KOTSU_00 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrTEHAI_KOTSU_00 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TdTEHAI_KOTSU_00 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdTEHAI_KOTSU_00 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TEHAI_KOTSU_Yes コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TEHAI_KOTSU_Yes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''TEHAI_KOTSU_No コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TEHAI_KOTSU_No As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''TrTEHAI_KOTSU_01 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrTEHAI_KOTSU_01 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TrTEHAI_KOTSU_02 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrTEHAI_KOTSU_02 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TrTEHAI_KOTSU_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrTEHAI_KOTSU_1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TdTEHAI_KOTSU_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdTEHAI_KOTSU_1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdTEHAI_KOTSU_O_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdTEHAI_KOTSU_O_1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''O_KOTSU_KUBUN_1_AIR コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_KOTSU_KUBUN_1_AIR As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''O_KOTSU_KUBUN_1_JR コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_KOTSU_KUBUN_1_JR As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''O_KOTSU_KUBUN_1_None コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_KOTSU_KUBUN_1_None As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''O_DATE_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_DATE_1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''O_BIN_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_BIN_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TblO_AIRPORT_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblO_AIRPORT_1 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''O_AIRPORT1_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_AIRPORT1_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''O_AIRPORT2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_AIRPORT2_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TblO_EXPRESS_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblO_EXPRESS_1 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''O_EXPRESS1_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_EXPRESS1_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''O_EXPRESS2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_EXPRESS2_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TblO_LOCAL_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblO_LOCAL_1 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''O_LOCAL1_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_LOCAL1_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''O_LOCAL2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_LOCAL2_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''O_TIME1_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_TIME1_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''O_TIME2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_TIME2_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TblO_SEAT_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblO_SEAT_1 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''O_SEAT_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_SEAT_1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TblO_SEATCLASS_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblO_SEATCLASS_1 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''O_SEATCLASS_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_SEATCLASS_1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TdTEHAI_KOTSU_F_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdTEHAI_KOTSU_F_1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''F_KOTSU_KUBUN_1_AIR コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_KOTSU_KUBUN_1_AIR As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''F_KOTSU_KUBUN_1_JR コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_KOTSU_KUBUN_1_JR As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''F_KOTSU_KUBUN_1_None コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_KOTSU_KUBUN_1_None As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''F_DATE_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_DATE_1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''F_BIN_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_BIN_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TblF_AIRPORT_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblF_AIRPORT_1 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''F_AIRPORT1_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_AIRPORT1_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''F_AIRPORT2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_AIRPORT2_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TblF_EXPRESS_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblF_EXPRESS_1 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''F_EXPRESS1_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_EXPRESS1_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''F_EXPRESS2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_EXPRESS2_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TblF_LOCAL_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblF_LOCAL_1 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''F_LOCAL1_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_LOCAL1_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''F_LOCAL2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_LOCAL2_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''F_TIME1_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_TIME1_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''F_TIME2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_TIME2_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TblF_SEAT_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblF_SEAT_1 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''F_SEAT_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_SEAT_1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TblF_SEATCLASS_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblF_SEATCLASS_1 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''F_SEATCLASS_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_SEATCLASS_1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TrTEHAI_KOTSU_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrTEHAI_KOTSU_2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TdTEHAI_KOTSU_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdTEHAI_KOTSU_2 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdTEHAI_KOTSU_O_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdTEHAI_KOTSU_O_2 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''O_KOTSU_KUBUN_2_AIR コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_KOTSU_KUBUN_2_AIR As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''O_KOTSU_KUBUN_2_JR コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_KOTSU_KUBUN_2_JR As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''O_KOTSU_KUBUN_2_None コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_KOTSU_KUBUN_2_None As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''O_DATE_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_DATE_2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''O_BIN_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_BIN_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TblO_AIRPORT_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblO_AIRPORT_2 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''O_AIRPORT1_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_AIRPORT1_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''O_AIRPORT2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_AIRPORT2_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TblO_EXPRESS_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblO_EXPRESS_2 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''O_EXPRESS1_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_EXPRESS1_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''O_EXPRESS2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_EXPRESS2_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TblO_LOCAL_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblO_LOCAL_2 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''O_LOCAL1_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_LOCAL1_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''O_LOCAL2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_LOCAL2_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''O_TIME1_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_TIME1_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''O_TIME2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_TIME2_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TblO_SEAT_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblO_SEAT_2 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''O_SEAT_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_SEAT_2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TblO_SEATCLASS_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblO_SEATCLASS_2 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''O_SEATCLASS_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_SEATCLASS_2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TdTEHAI_KOTSU_F_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdTEHAI_KOTSU_F_2 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''F_KOTSU_KUBUN_2_AIR コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_KOTSU_KUBUN_2_AIR As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''F_KOTSU_KUBUN_2_JR コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_KOTSU_KUBUN_2_JR As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''F_KOTSU_KUBUN_2_None コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_KOTSU_KUBUN_2_None As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''F_DATE_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_DATE_2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''F_BIN_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_BIN_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TblF_AIRPORT_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblF_AIRPORT_2 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''F_AIRPORT1_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_AIRPORT1_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''F_AIRPORT2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_AIRPORT2_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TblF_EXPRESS_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblF_EXPRESS_2 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''F_EXPRESS1_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_EXPRESS1_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''F_EXPRESS2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_EXPRESS2_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TblF_LOCAL_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblF_LOCAL_2 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''F_LOCAL1_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_LOCAL1_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''F_LOCAL2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_LOCAL2_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''F_TIME1_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_TIME1_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''F_TIME2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_TIME2_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TblF_SEAT_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblF_SEAT_2 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''F_SEAT_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_SEAT_2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TblF_SEATCLASS_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblF_SEATCLASS_2 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''F_SEATCLASS_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_SEATCLASS_2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TrTEHAI_KOTSU_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrTEHAI_KOTSU_3 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TdTEHAI_KOTSU_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdTEHAI_KOTSU_3 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdTEHAI_KOTSU_O_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdTEHAI_KOTSU_O_3 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''O_KOTSU_KUBUN_3_AIR コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_KOTSU_KUBUN_3_AIR As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''O_KOTSU_KUBUN_3_JR コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_KOTSU_KUBUN_3_JR As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''O_KOTSU_KUBUN_3_None コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_KOTSU_KUBUN_3_None As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''O_DATE_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_DATE_3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''O_BIN_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_BIN_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TblO_AIRPORT_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblO_AIRPORT_3 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''O_AIRPORT1_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_AIRPORT1_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''O_AIRPORT2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_AIRPORT2_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TblO_EXPRESS_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblO_EXPRESS_3 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''O_EXPRESS1_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_EXPRESS1_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''O_EXPRESS2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_EXPRESS2_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TblO_LOCAL_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblO_LOCAL_3 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''O_LOCAL1_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_LOCAL1_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''O_LOCAL2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_LOCAL2_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''O_TIME1_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_TIME1_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''O_TIME2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_TIME2_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TblO_SEAT_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblO_SEAT_3 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''O_SEAT_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_SEAT_3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TblO_SEATCLASS_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblO_SEATCLASS_3 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''O_SEATCLASS_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents O_SEATCLASS_3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TdTEHAI_KOTSU_F_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdTEHAI_KOTSU_F_3 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''F_KOTSU_KUBUN_3_AIR コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_KOTSU_KUBUN_3_AIR As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''F_KOTSU_KUBUN_3_JR コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_KOTSU_KUBUN_3_JR As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''F_KOTSU_KUBUN_3_None コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_KOTSU_KUBUN_3_None As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''F_DATE_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_DATE_3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''F_BIN_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_BIN_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TblF_AIRPORT_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblF_AIRPORT_3 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''F_AIRPORT1_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_AIRPORT1_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''F_AIRPORT2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_AIRPORT2_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TblF_EXPRESS_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblF_EXPRESS_3 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''F_EXPRESS1_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_EXPRESS1_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''F_EXPRESS2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_EXPRESS2_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TblF_LOCAL_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblF_LOCAL_3 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''F_LOCAL1_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_LOCAL1_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''F_LOCAL2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_LOCAL2_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''F_TIME1_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_TIME1_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''F_TIME2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_TIME2_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TblF_SEAT_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblF_SEAT_3 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''F_SEAT_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_SEAT_3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TblF_SEATCLASS_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblF_SEATCLASS_3 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''F_SEATCLASS_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents F_SEATCLASS_3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TrTEHAI_KOTSU_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrTEHAI_KOTSU_4 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TdTEHAI_KOTSU_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdTEHAI_KOTSU_4 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''AIRLINE_ANA コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents AIRLINE_ANA As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''AIRLINE_JAL コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents AIRLINE_JAL As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''MILAGE_NO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents MILAGE_NO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TrTEHAI_KOTSU_5 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrTEHAI_KOTSU_5 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TdTEHAI_KOTSU_5 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdTEHAI_KOTSU_5 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''NOTE_KOTSU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents NOTE_KOTSU As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TdSEND_SAKI_0 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdSEND_SAKI_0 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''SEND_SAKI コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SEND_SAKI As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TrSEND_SAKI_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrSEND_SAKI_1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TdSEND_SAKI_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdSEND_SAKI_1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''SEND_ZIP_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SEND_ZIP_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SEND_ZIP_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SEND_ZIP_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SEND_ADDRESS コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SEND_ADDRESS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TrSEND_SAKI_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrSEND_SAKI_2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TdSEND_SAKI_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdSEND_SAKI_3 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''SEND_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SEND_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TrSEND_SAKI_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrSEND_SAKI_3 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TdSEND_SAKI_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdSEND_SAKI_4 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''SEND_TEL_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SEND_TEL_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SEND_TEL_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SEND_TEL_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SEND_TEL_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SEND_TEL_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TrPAYMENT_METHOD コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrPAYMENT_METHOD As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''PAYMENT_METHOD_Card コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents PAYMENT_METHOD_Card As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''PAYMENT_METHOD_Bank コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents PAYMENT_METHOD_Bank As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''NOTES コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents NOTES As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnConfirm コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnConfirm As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master プロパティ。
    '''</summary>
    '''<remarks>
    '''自動生成されたプロパティ。
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Bayer.Base
        Get
            Return CType(MyBase.Master, Bayer.Base)
        End Get
    End Property
End Class
