'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.5472
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class DrRegist

    '''<summary>
    '''BtnCancel コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ImgCanceled コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ImgCanceled As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''BtnNozomi コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnNozomi As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnKihon コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnKihon As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Tr1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Tr1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''KOUENKAI_NO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KOUENKAI_NO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KOUENKAI_FROM_DATE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KOUENKAI_FROM_DATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KOUENKAI_TO_DATE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KOUENKAI_TO_DATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Tr2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Tr2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''KOUENKAI_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KOUENKAI_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TAXI_PRT_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TAXI_PRT_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MR_JIGYOBU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents MR_JIGYOBU As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MR_AREA コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents MR_AREA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MR_EIGYOSHO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents MR_EIGYOSHO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MR_NO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents MR_NO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MR_KEITAI コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents MR_KEITAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MR_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents MR_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MR_EMAIL コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents MR_EMAIL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MR_SEND_SAKI_FS コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents MR_SEND_SAKI_FS As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MR_SEND_SAKI_OTHER コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents MR_SEND_SAKI_OTHER As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DR_MPID コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DR_MPID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DR_CD コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DR_CD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UPDATE_DATE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UPDATE_DATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''STATUS_TEHAI コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents STATUS_TEHAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DR_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DR_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DR_KANA コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DR_KANA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DR_SEX コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DR_SEX As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DR_SANKA コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DR_SANKA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SHONIN_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SHONIN_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SHONIN_DATE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SHONIN_DATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SHONIN_NOTE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SHONIN_NOTE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CMSHONIN_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents CMSHONIN_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CMSHONIN_DATE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents CMSHONIN_DATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CMSHONIN_NOTE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents CMSHONIN_NOTE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TblMust コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TblMust As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''TEHAI_HOTEL コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TEHAI_HOTEL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ANS_STATUS_HOTEL コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_STATUS_HOTEL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''HOTEL_IRAINAIYOU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HOTEL_IRAINAIYOU As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ANS_HOTEL_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_HOTEL_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnHotelKensaku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnHotelKensaku As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''REQ_HOTEL_DATE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_HOTEL_DATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''REQ_HAKUSU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_HAKUSU As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ANS_HOTEL_ADDRESS コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_HOTEL_ADDRESS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REQ_HOTEL_SMOKING コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_HOTEL_SMOKING As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ANS_HOTEL_TEL コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_HOTEL_TEL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REQ_HOTEL_NOTE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_HOTEL_NOTE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ANS_CHECKIN_TIME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_CHECKIN_TIME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ANS_CHECKOUT_TIME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_CHECKOUT_TIME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ANS_HOTEL_DATE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_HOTEL_DATE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ANS_HAKUSU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_HAKUSU As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ANS_ROOM_TYPE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_ROOM_TYPE As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ANS_ROOM_CHARGE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_ROOM_CHARGE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ANS_HOTEL_SMOKING_YES コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_HOTEL_SMOKING_YES As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''ANS_HOTEL_SMOKING_NO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_HOTEL_SMOKING_NO As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''ANS_HOTEL_NOTE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_HOTEL_NOTE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnKOTSU_O_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnKOTSU_O_1 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''REQ_O_TEHAI_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_TEHAI_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ANS_O_STATUS_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_STATUS_1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TB_KOTSU_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TB_KOTSU_1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''BtnCopy_O_TEHAI_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnCopy_O_TEHAI_1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''REQ_O_IRAINAIYOU_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_IRAINAIYOU_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''REQ_O_KOTSUKIKAN_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_KOTSUKIKAN_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ANS_O_KOTSUKIKAN_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_KOTSUKIKAN_1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''REQ_O_DATE_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_DATE_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ANS_O_DATE_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_DATE_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REQ_O_AIRPORT1_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_AIRPORT1_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REQ_O_AIRPORT2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_AIRPORT2_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ANS_O_AIRPORT1_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_AIRPORT1_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ANS_O_AIRPORT2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_AIRPORT2_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REQ_O_TIME1_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_TIME1_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REQ_O_TIME2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_TIME2_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ANS_O_TIME1_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_TIME1_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ANS_O_TIME2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_TIME2_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REQ_O_BIN_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_BIN_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ANS_O_BIN_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_BIN_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REQ_O_SEAT_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_SEAT_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REQ_O_AGE_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_AGE_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ANS_O_SEAT_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_SEAT_1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ANS_O_AGE_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_AGE_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnKOTSU_O_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnKOTSU_O_2 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''REQ_O_TEHAI_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_TEHAI_2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ANS_O_STATUS_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_STATUS_2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TB_KOTSU_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TB_KOTSU_2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''BtnCopy_O_TEHAI_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnCopy_O_TEHAI_2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''REQ_O_IRAINAIYOU_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_IRAINAIYOU_2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''REQ_O_KOTSUKIKAN_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_KOTSUKIKAN_2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ANS_O_KOTSUKIKAN_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_KOTSUKIKAN_2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''REQ_O_DATE_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_DATE_2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ANS_O_DATE_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_DATE_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REQ_O_AIRPORT1_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_AIRPORT1_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REQ_O_AIRPORT2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_AIRPORT2_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ANS_O_AIRPORT1_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_AIRPORT1_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ANS_O_AIRPORT2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_AIRPORT2_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REQ_O_TIME1_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_TIME1_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REQ_O_TIME2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_TIME2_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ANS_O_TIME1_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_TIME1_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ANS_O_TIME2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_TIME2_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REQ_O_BIN_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_BIN_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ANS_O_BIN_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_BIN_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REQ_O_SEAT_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_SEAT_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REQ_O_AGE_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_AGE_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ANS_O_SEAT_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_SEAT_2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ANS_O_AGE_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_AGE_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnKOTSU_O_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnKOTSU_O_3 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''REQ_O_TEHAI_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_TEHAI_3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ANS_O_STATUS_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_STATUS_3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TB_KOTSU_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TB_KOTSU_3 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''BtnCopy_O_TEHAI_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnCopy_O_TEHAI_3 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''REQ_O_IRAINAIYOU_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_IRAINAIYOU_3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''REQ_O_KOTSUKIKAN_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_KOTSUKIKAN_3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ANS_O_KOTSUKIKAN_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_KOTSUKIKAN_3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''REQ_O_DATE_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_DATE_3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ANS_O_DATE_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_DATE_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REQ_O_AIRPORT1_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_AIRPORT1_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REQ_O_AIRPORT2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_AIRPORT2_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ANS_O_AIRPORT1_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_AIRPORT1_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ANS_O_AIRPORT2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_AIRPORT2_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REQ_O_TIME1_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_TIME1_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REQ_O_TIME2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_TIME2_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ANS_O_TIME1_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_TIME1_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ANS_O_TIME2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_TIME2_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REQ_O_BIN_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_BIN_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ANS_O_BIN_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_BIN_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REQ_O_SEAT_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_SEAT_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REQ_O_AGE_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents REQ_O_AGE_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ANS_O_SEAT_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_SEAT_3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ANS_O_AGE_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_O_AGE_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnConfirm コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnConfirm As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master プロパティ。
    '''</summary>
    '''<remarks>
    '''自動生成されたプロパティ。
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Bayer.Base
        Get
            Return CType(MyBase.Master, Bayer.Base)
        End Get
    End Property
End Class
