'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.5472
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class KaijoList

    '''<summary>
    '''KIKAKU_TANTO_ROMA コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIKAKU_TANTO_ROMA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TEHAI_TANTO_ROMA コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TEHAI_TANTO_ROMA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SEIHIN_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SEIHIN_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''KOUENKAI_NO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KOUENKAI_NO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''KOUENKAI_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KOUENKAI_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FROM_DATE_YYYY コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents FROM_DATE_YYYY As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FROM_DATE_MM コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents FROM_DATE_MM As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FROM_DATE_DD コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents FROM_DATE_DD As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TO_DATE_YYYY コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TO_DATE_YYYY As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TO_DATE_MM コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TO_DATE_MM As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TO_DATE_DD コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TO_DATE_DD As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''KIKAKU_TANTO_BU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIKAKU_TANTO_BU As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''KIKAKU_TANTO_AREA コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIKAKU_TANTO_AREA As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TTANTO_ID コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TTANTO_ID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnSearch コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LabelNoData コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents LabelNoData As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GrvList コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents GrvList As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SqlDataSource1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''BtnBack コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnBack As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master プロパティ。
    '''</summary>
    '''<remarks>
    '''自動生成されたプロパティ。
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Bayer.Base
        Get
            Return CType(MyBase.Master, Bayer.Base)
        End Get
    End Property
End Class
