'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.5472
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class KouenkaiRegist

    '''<summary>
    '''KOUENKAI_NO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KOUENKAI_NO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ANS_STATUS_TEHAI コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ANS_STATUS_TEHAI As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''YOTEI_DATE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents YOTEI_DATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KAISAI_DATE_NOTE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KAISAI_DATE_NOTE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SHONIN_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SHONIN_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SHONIN_TIME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SHONIN_TIME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KOUENKAI_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KOUENKAI_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TAXI_PRT_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TAXI_PRT_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SEIHIN_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SEIHIN_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KIKAKU_TANTO_JIGYOBU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIKAKU_TANTO_JIGYOBU As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KIKAKU_TANTO_AREA コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIKAKU_TANTO_AREA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KIKAKU_TANTO_EIGYOSHO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIKAKU_TANTO_EIGYOSHO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KIKAKU_TANTO_NO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIKAKU_TANTO_NO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KIKAKU_TANTO_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIKAKU_TANTO_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KIKAKU_TANTO_KEITAI コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIKAKU_TANTO_KEITAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KIKAKU_TANTO_EMAIL コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIKAKU_TANTO_EMAIL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TEHAI_TANTO_JIGYOBU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TEHAI_TANTO_JIGYOBU As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TEHAI_TANTO_AREA コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TEHAI_TANTO_AREA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TEHAI_TANTO_EIGYOSHO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TEHAI_TANTO_EIGYOSHO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TEHAI_TANTO_NO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TEHAI_TANTO_NO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TEHAI_TANTO_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TEHAI_TANTO_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TEHAI_TANTO_KEITAI コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TEHAI_TANTO_KEITAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TEHAI_TANTO_EMAIL コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TEHAI_TANTO_EMAIL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MITSUMORI_TF コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents MITSUMORI_TF As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''予算額費用1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents 予算額費用1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''予算額費用2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents 予算額費用2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''実施費用計 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents 実施費用計 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BtnRireki コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnRireki As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnToroku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnToroku As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnNozomi コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnNozomi As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnCancel コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master プロパティ。
    '''</summary>
    '''<remarks>
    '''自動生成されたプロパティ。
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Bayer.Base
        Get
            Return CType(MyBase.Master, Bayer.Base)
        End Get
    End Property
End Class
