'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.5472
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class KouenkaiRegist

    '''<summary>
    '''BtnSubmit1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnSubmit1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnBack1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnBack1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''KOUENKAI_NO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KOUENKAI_NO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KIDOKU_FLG コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIDOKU_FLG As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TORIKESHI_FLG コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TORIKESHI_FLG As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TIME_STAMP コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TIME_STAMP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KOUENKAI_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KOUENKAI_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TAXI_PRT_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TAXI_PRT_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FROM_DATE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents FROM_DATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KAIJO_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KAIJO_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SEIHIN_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SEIHIN_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''INTERNAL_ORDER_T コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents INTERNAL_ORDER_T As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''INTERNAL_ORDER_TF コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents INTERNAL_ORDER_TF As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ACCOUNT_CD_T コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ACCOUNT_CD_T As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ACCOUNT_CD_TF コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ACCOUNT_CD_TF As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ZETIA_CD コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ZETIA_CD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SANKA_YOTEI_CNT_MBR コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SANKA_YOTEI_CNT_MBR As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SANKA_YOTEI_CNT_NMBR コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SANKA_YOTEI_CNT_NMBR As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TTEHAI_TANTO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TTEHAI_TANTO As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DANTAI_CODE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DANTAI_CODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''KIKAKU_TANTO_JIGYOUBU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIKAKU_TANTO_JIGYOUBU As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BU As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KIKAKU_TANTO_AREA コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIKAKU_TANTO_AREA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''KIKAKU_TANTO_EIGYOSHO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIKAKU_TANTO_EIGYOSHO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''COST_CENTER コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents COST_CENTER As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KIKAKU_TANTO_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIKAKU_TANTO_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''KIKAKU_TANTO_ROMA コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIKAKU_TANTO_ROMA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''KIKAKU_TANTO_TEL コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIKAKU_TANTO_TEL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KIKAKU_TANTO_KEITAI コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIKAKU_TANTO_KEITAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KIKAKU_TANTO_EMAIL コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIKAKU_TANTO_EMAIL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''KIKAKU_TANTO_EMAIL_KEITAI コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIKAKU_TANTO_EMAIL_KEITAI As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''YOSAN_TF コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents YOSAN_TF As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''YOSAN_T コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents YOSAN_T As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''IROUKAI_YOSAN_T コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents IROUKAI_YOSAN_T As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''IKENKOUKAN_YOSAN_T コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents IKENKOUKAN_YOSAN_T As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BtnRireki コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnRireki As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnSubmit2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnSubmit2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnNozomi コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnNozomi As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnBack2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnBack2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master プロパティ。
    '''</summary>
    '''<remarks>
    '''自動生成されたプロパティ。
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Bayer.Base
        Get
            Return CType(MyBase.Master, Bayer.Base)
        End Get
    End Property
End Class
