'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.5472
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class SeisanRegist

    '''<summary>
    '''BtnPrint1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnPrint1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnCancel1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnCancel1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''SEND_FLAG コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SEND_FLAG As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DivMessage コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DivMessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LabelMessage コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents LabelMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KOUENKAI_NO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KOUENKAI_NO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SEISAN_YM コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SEISAN_YM As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SEIKYU_NO_TOPTOUR コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SEIKYU_NO_TOPTOUR As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SHIHARAI_NO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SHIHARAI_NO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SHOUNIN_KUBUN コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SHOUNIN_KUBUN As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SHOUNIN_DATE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SHOUNIN_DATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KAIJOHI_TF コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KAIJOHI_TF As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''KIZAIHI_TF コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIZAIHI_TF As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''INSHOKUHI_TF コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents INSHOKUHI_TF As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''KEI_991330401_TF コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KEI_991330401_TF As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HOTELHI_TF コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HOTELHI_TF As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HOTELHI_TOZEI コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HOTELHI_TOZEI As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''JR_TF コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents JR_TF As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AIR_TF コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents AIR_TF As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''OTHER_TRAFFIC_TF コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents OTHER_TRAFFIC_TF As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TAXI_COMMISSION_TF コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TAXI_COMMISSION_TF As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HOTEL_COMMISSION_TF コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HOTEL_COMMISSION_TF As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''JINKENHI_TF コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents JINKENHI_TF As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''OTHER_TF コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents OTHER_TF As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''KANRIHI_TF コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KANRIHI_TF As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TAXI_TF コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TAXI_TF As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TAXI_SEISAN_TF コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TAXI_SEISAN_TF As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''KEI_41120200_TF コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KEI_41120200_TF As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KEI_TF コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KEI_TF As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KAIJOUHI_T コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KAIJOUHI_T As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''KIZAIHI_T コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KIZAIHI_T As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''INSHOKUHI_T コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents INSHOKUHI_T As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''KEI_991330401_T コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KEI_991330401_T As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''JINKENHI_T コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents JINKENHI_T As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''OTHER_T コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents OTHER_T As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''KANRIHI_T コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KANRIHI_T As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''KEI_41120200_T コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KEI_41120200_T As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KEI_T コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KEI_T As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MR_HOTEL コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents MR_HOTEL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MR_HOTEL_TOZEI コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents MR_HOTEL_TOZEI As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MR_JR コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents MR_JR As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SEISANSHO_URL コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SEISANSHO_URL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TAXI_T コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TAXI_T As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TAXI_SEISAN_T コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TAXI_SEISAN_T As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TAXI_TICKET_URL コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TAXI_TICKET_URL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SEISAN_KANRYO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SEISAN_KANRYO As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''BtnDrCsv コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnDrCsv As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnDrCsvHid コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnDrCsvHid As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnMrCsv コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnMrCsv As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnMrCsvHid コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnMrCsvHid As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnTaxiCsv コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnTaxiCsv As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnCalc コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnSubmit コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnSubmit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnNozomi コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnNozomi As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnPrint2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnPrint2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnCancel2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnCancel2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master プロパティ。
    '''</summary>
    '''<remarks>
    '''自動生成されたプロパティ。
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Bayer.Base
        Get
            Return CType(MyBase.Master, Bayer.Base)
        End Get
    End Property
End Class
