USE [BAYER_DEMO]
GO
/****** オブジェクト:  Table [dbo].[MS_BU]    ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MS_BU](
	[SYSTEM_ID] [nvarchar](10) COLLATE Japanese_CI_AS NULL,
	[BU] [nvarchar](40) COLLATE Japanese_CI_AS NOT NULL,
	[STOP_FLG] [nvarchar](1) COLLATE Japanese_CI_AS NULL,
	[INPUT_DATE] [nvarchar](14) COLLATE Japanese_CI_AS NULL,
	[INPUT_USER] [nvarchar](20) COLLATE Japanese_CI_AS NULL,
	[UPDATE_DATE] [nvarchar](14) COLLATE Japanese_CI_AS NULL,
	[UPDATE_USER] [nvarchar](20) COLLATE Japanese_CI_AS NULL,
 CONSTRAINT [PK_MS_BU] PRIMARY KEY CLUSTERED 
(
	[BU] ASC
) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF