USE [BAYER_DEMO]
GO
/****** オブジェクト:  Table [dbo].[MS_CODE]    ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MS_CODE](
	[CODE] [nvarchar](2) COLLATE Japanese_CI_AS  NOT NULL,
	[DATA_ID] [nvarchar](2) COLLATE Japanese_CI_AS  NOT NULL,
	[DISP_TEXT] [nvarchar](80) COLLATE Japanese_CI_AS  NULL,
	[DISP_VALUE] [nvarchar](80) COLLATE Japanese_CI_AS  NULL,
 CONSTRAINT [PK_MS_USER] PRIMARY KEY CLUSTERED 
(
	[CODE] ASC,
	[DATA_ID] ASC
) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF


