USE [BAYER_DEMO]
GO
/****** オブジェクト:  Table [dbo].[TBL_SHOUNIN]    ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TBL_SHOUNIN](
	[KOUENKAI_NO] [nvarchar](14) COLLATE Japanese_CI_AS  NOT NULL,
	[SEIKYU_NO_TOPTOUR] [nvarchar](14) COLLATE Japanese_CI_AS  NOT NULL,
	[SHIHARAI_NO] [nvarchar](14) COLLATE Japanese_CI_AS  NULL,
	[SHOUNIN_KUBUN] [nvarchar](1) COLLATE Japanese_CI_AS  NULL,
	[SHOUNIN_DATE] [nvarchar](8) COLLATE Japanese_CI_AS  NULL,
	[INPUT_DATE] [nvarchar](14) COLLATE Japanese_CI_AS  NULL,
	[INPUT_USER] [nvarchar](20) COLLATE Japanese_CI_AS  NULL,
	[UPDATE_DATE] [nvarchar](14) COLLATE Japanese_CI_AS  NULL,
	[UPDATE_USER] [nvarchar](20) COLLATE Japanese_CI_AS  NULL,
 CONSTRAINT [PK_TBL_SHOUNIN] PRIMARY KEY CLUSTERED 
(
	[KOUENKAI_NO] ASC,
	[SEIKYU_NO_TOPTOUR] ASC
) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
