USE [BAYER_DEMO]
GO
/****** オブジェクト:  Table [dbo].[TBL_SANKA]    ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TBL_SANKA](
	[KOUENKAI_NO] [nvarchar](14) COLLATE Japanese_CI_AS  NOT NULL,
	[SANKASHA_ID] [nvarchar](14) COLLATE Japanese_CI_AS  NOT NULL,
	[DR_SANKA] [nvarchar](1) COLLATE Japanese_CI_AS  NULL,
	[INPUT_DATE] [nvarchar](14) COLLATE Japanese_CI_AS  NULL,
	[INPUT_USER] [nvarchar](20) COLLATE Japanese_CI_AS  NULL,
	[UPDATE_DATE] [nvarchar](14) COLLATE Japanese_CI_AS  NULL,
	[UPDATE_USER] [nvarchar](20) COLLATE Japanese_CI_AS  NULL,
 CONSTRAINT [PK_TBL_SANKA] PRIMARY KEY CLUSTERED 
(
	[KOUENKAI_NO] ASC,
	[SANKASHA_ID] ASC
) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
