USE [BAYER_DEMO]
GO
/****** オブジェクト:  Table [dbo].[TBL_SEIKYU]    ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TBL_SEIKYU](
	[KOUENKAI_NO] [nvarchar](14) COLLATE Japanese_CI_AS  NOT NULL,
	[SEISAN_YM] [nvarchar](8) COLLATE Japanese_CI_AS  NOT NULL,
	[PAYMENT_NO] [nvarchar](80) COLLATE Japanese_CI_AS  NOT NULL,
	[SHOUNIN_KUBUN] [nvarchar](1) COLLATE Japanese_CI_AS  NULL,
	[SHOUNIN_DATE] [nvarchar](8) COLLATE Japanese_CI_AS  NULL,
	[KAIJOHI_TF] [nvarchar](10) COLLATE Japanese_CI_AS  NULL,
	[KIZAIHI_TF] [nvarchar](10) COLLATE Japanese_CI_AS  NULL,
	[INSHOKUHI_TF] [nvarchar](10) COLLATE Japanese_CI_AS  NULL,
	[KEI_99133040_1] [nvarchar](10) COLLATE Japanese_CI_AS  NULL,
	[UNEIHI_TF] [nvarchar](10) COLLATE Japanese_CI_AS  NULL,
	[JINKENHI_TF] [nvarchar](10) COLLATE Japanese_CI_AS  NULL,
	[KEI_41120200_1] [nvarchar](10) COLLATE Japanese_CI_AS  NULL,
	[HOTELHI_TF] [nvarchar](10) COLLATE Japanese_CI_AS  NULL,
	[JR_TF] [nvarchar](10) COLLATE Japanese_CI_AS  NULL,
	[OTHER_TF] [nvarchar](10) COLLATE Japanese_CI_AS  NULL,
	[HOTEL_COMMISSION_TF] [nvarchar](10) COLLATE Japanese_CI_AS  NULL,
	[TAXI_COMMISSION_TF] [nvarchar](10) COLLATE Japanese_CI_AS  NULL,
	[TAXI_TF] [nvarchar](10) COLLATE Japanese_CI_AS  NULL,
	[TAXI_SEISAN_TF] [nvarchar](10) COLLATE Japanese_CI_AS  NULL,
	[KEI_41120200_2] [nvarchar](10) COLLATE Japanese_CI_AS  NULL,
	[KEI_TF] [nvarchar](10) COLLATE Japanese_CI_AS  NULL,
	[KAIJOUHI_T] [nvarchar](10) COLLATE Japanese_CI_AS  NULL,
	[KIZAIHI_T] [nvarchar](10) COLLATE Japanese_CI_AS  NULL,
	[INSHOKUHI_T] [nvarchar](10) COLLATE Japanese_CI_AS  NULL,
	[KEI_99133040_2] [nvarchar](10) COLLATE Japanese_CI_AS  NULL,
	[KEI_T] [nvarchar](10) COLLATE Japanese_CI_AS  NULL,
	[SEIKYU_NO_TOPTOUR] [nvarchar](100) COLLATE Japanese_CI_AS  NULL,
	[TAXI_T] [nvarchar](10) COLLATE Japanese_CI_AS  NULL,
	[TAXI_SEISAN_T] [nvarchar](10) COLLATE Japanese_CI_AS  NULL,
	[TAXI_TICKET_URL] [nvarchar](255) COLLATE Japanese_CI_AS  NULL,
	[MR_JR_1] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_JR_2] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_JR_3] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_JR_4] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_JR_5] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_JR_6] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_JR_7] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_JR_8] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_JR_9] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_JR_10] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_JR_11] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_JR_12] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_JR_13] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_JR_14] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_JR_15] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_HOTEL_1] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_HOTEL_2] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_HOTEL_3] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_HOTEL_4] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_HOTEL_5] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_HOTEL_6] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_HOTEL_7] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_HOTEL_8] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_HOTEL_9] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_HOTEL_10] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_HOTEL_11] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_HOTEL_12] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_HOTEL_13] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_HOTEL_14] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[MR_HOTEL_15] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_TF_1] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_TF_2] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_TF_3] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_TF_4] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_TF_5] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_TF_6] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_TF_7] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_TF_8] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_TF_9] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_TF_10] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_TF_11] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_TF_12] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_TF_13] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_TF_14] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_TF_15] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_SEISAN_TF_1] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_SEISAN_TF_2] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_SEISAN_TF_3] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_SEISAN_TF_4] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_SEISAN_TF_5] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_SEISAN_TF_6] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_SEISAN_TF_7] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_SEISAN_TF_8] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_SEISAN_TF_9] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_SEISAN_TF_10] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_SEISAN_TF_11] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_SEISAN_TF_12] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_SEISAN_TF_13] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_SEISAN_TF_14] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[TAXI_SEISAN_TF_15] [nvarchar](12) COLLATE Japanese_CI_AS  NULL,
	[KOUENKAI_KUBUN] [nvarchar](1) COLLATE Japanese_CI_AS  NULL,
	[DELETE_FLAG] [nvarchar](1) COLLATE Japanese_CI_AS  NULL,
	[SEND_FLAG] [nvarchar](1) COLLATE Japanese_CI_AS  NULL,
	[TTANTO_ID] [nvarchar](10) COLLATE Japanese_CI_AS  NULL,
	[INPUT_DATE] [nvarchar](14) COLLATE Japanese_CI_AS  NULL,
	[INPUT_USER] [nvarchar](20) COLLATE Japanese_CI_AS  NULL,
	[UPDATE_DATE] [nvarchar](14) COLLATE Japanese_CI_AS  NULL,
	[UPDATE_USER] [nvarchar](20) COLLATE Japanese_CI_AS  NULL,
 CONSTRAINT [PK_TBL_SEIKYU] PRIMARY KEY CLUSTERED 
(
	[KOUENKAI_NO] ASC
) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF