'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.5485
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class TaxiMaintenanceRegist

    '''<summary>
    '''BtnBack1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnBack1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''KOUENKAI_NO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KOUENKAI_NO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KOUENKAI_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KOUENKAI_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TAXI_PRT_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TAXI_PRT_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KOUENKAI_DATE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KOUENKAI_DATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TTEHAI_TANTO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TTEHAI_TANTO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TbFurikae コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TbFurikae As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''KOUENKAI_NO_FURIKAE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KOUENKAI_NO_FURIKAE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnKaigou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnKaigou As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''KOUENKAI_NAME_FURIKAE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KOUENKAI_NAME_FURIKAE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TAXI_PRT_NAME_FURIKAE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TAXI_PRT_NAME_FURIKAE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KOUENKAI_DATE_FURIKAE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KOUENKAI_DATE_FURIKAE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TTEHAI_TANTO_FURIKAE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TTEHAI_TANTO_FURIKAE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SANKASHA_ID コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SANKASHA_ID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnSankasha コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnSankasha As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DR_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DR_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DR_KANA コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DR_KANA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DR_SEX コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DR_SEX As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DR_AGE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DR_AGE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DR_SANKA コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DR_SANKA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DR_YAKUWARI コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DR_YAKUWARI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DR_SHISETSU_CD コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DR_SHISETSU_CD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DR_SHISETSU_NAME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DR_SHISETSU_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DR_SHISETSU_ADDRESS コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DR_SHISETSU_ADDRESS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SHITEIGAI_RIYU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SHITEIGAI_RIYU As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TbTaxi コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TbTaxi As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''TKT_LINE_NO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TKT_LINE_NO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TKT_NO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TKT_NO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TKT_KAISHA コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TKT_KAISHA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TKT_KENSHU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TKT_KENSHU As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TKT_USED_DATE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TKT_USED_DATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VOID_DATE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents VOID_DATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TKT_SEIKYU_YM コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TKT_SEIKYU_YM As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TKT_VOID コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TKT_VOID As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''TKT_HATUTI コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TKT_HATUTI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TKT_CHAKUTI コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TKT_CHAKUTI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TbTaxiMaintenance コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TbTaxiMaintenance As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''TKT_LINE_NO_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TKT_LINE_NO_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TKT_NO_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TKT_NO_2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TKT_KAISHA_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TKT_KAISHA_2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TKT_KENSHU_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TKT_KENSHU_2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TKT_USED_DATE_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TKT_USED_DATE_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TKT_SEIKYU_YM_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TKT_SEIKYU_YM_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''VOID_DATE_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents VOID_DATE_2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TKT_VOID_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TKT_VOID_2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''TKT_HATUTI_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TKT_HATUTI_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TKT_CHAKUTI_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TKT_CHAKUTI_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TKT_URIAGE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TKT_URIAGE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TKT_SEISAN_FEE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TKT_SEISAN_FEE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TKT_HAKKO_FEE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TKT_HAKKO_FEE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TKT_ENTA コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TKT_ENTA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SEIKYU_NO_TOPTOUR コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SEIKYU_NO_TOPTOUR As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnSubmit コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnSubmit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnBack2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnBack2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master プロパティ。
    '''</summary>
    '''<remarks>
    '''自動生成されたプロパティ。
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Bayer.Base
        Get
            Return CType(MyBase.Master, Bayer.Base)
        End Get
    End Property
End Class
