Public Class SessionDef
    'セッション変数名 定義
    Public Const TBL_KOUENKAI As String = "TBL_KOUENKAI"
    Public Const TBL_SEIKYU As String = "TBL_SEIKYU"
    Public Const TBL_KOTSUHOTEL As String = "TBL_KOTSUHOTEL"
    Public Const TBL_KAIJO As String = "TBL_KAIJO"
    Public Const TBL_BENTO As String = "TBL_BENTO"
    Public Const TBL_LOG As String = "TBL_LOG"
    Public Const MS_USER As String = "MS_USER"
    Public Const MS_SHISETSU As String = "MS_SHISETSU"
    Public Const MS_JIGYOSHO As String = "MS_JIGYOSHO"
    Public Const MS_AREA As String = "MS_AREA"
    Public Const MS_EIGYOSHO As String = "MS_EIGYOSHO"
    Public Const MS_CODE As String = "MS_CODE"
    Public Const RECORD_KUBUN As String = "RECORD_KUBUN"
    Public Const SEQ As String = "SEQ"
    Public Const PageIndex As String = "PageIndex"
    Public Const BackURL As String = "BackURL"
    Public Const DbError As String = "DbError"
    Public Const LoginID As String = "LoginID"
    Public Const Joken As String = "Joken"
    Public Const SYSTEM_ID As String = "SYSTEM_ID"
    Public Const HotelKensaku_ADDRESS1 As String = "HotelKensaku_ADDRESS1"
    Public Const HotelKensaku_ADDRESS2 As String = "HotelKensaku_ADDRESS2"
    Public Const HotelKensaku_SHISETSU_NAME As String = "HotelKensaku_SHISETSU_NAME"
    Public Const HotelKensaku_SHISETSU_NAME_KANA As String = "HotelKensaku_SHISETSU_NAME_KANA"
    Public Const HotelKensaku_ADDRESS As String = "HotelKensaku_ADDRESS"
    Public Const HotelKensaku_TEL As String = "HotelKensaku_TEL"
    Public Const HotelKensaku_URL As String = "HotelKensaku_URL"
    Public Const ShisetsuKensaku_ZIP As String = "ShisetsuKensaku_ZIP"
    Public Const ShisetsuKensaku_ADDRESS1 As String = "ShisetsuKensaku_ADDRESS1"
    Public Const ShisetsuKensaku_ADDRESS2 As String = "ShisetsuKensaku_ADDRESS2"
    Public Const ShisetsuKensaku_SHISETSU_NAME As String = "ShisetsuKensaku_SHISETSU_NAME"
    Public Const ShisetsuKensaku_SHISETSU_NAME_KANA As String = "ShisetsuKensaku_SHISETSU_NAME_KANA"
    Public Const ShisetsuKensaku_ADDRESS As String = "ShisetsuKensaku_ADDRESS"
    Public Const ShisetsuKensaku_TEL As String = "ShisetsuKensaku_TEL"
    Public Const ShisetsuKensaku_URL As String = "ShisetsuKensaku_URL"
End Class
