Public Class SessionDef
    'セッション変数名 定義
    Public Const TBL_KOUENKAI As String = "TBL_KOUENKAI"
    Public Const TBL_SEIKYU As String = "TBL_SEIKYU"
    Public Const TBL_KOTSUHOTEL As String = "TBL_KOTSUHOTEL"
    Public Const TBL_KAIJO As String = "TBL_KAIJO"
    Public Const TBL_BENTO As String = "TBL_BENTO"
    Public Const MS_USER As String = "MS_USER"
    Public Const MS_SHISETSU As String = "MS_SHISETSU"
    Public Const MS_JIGYOSHO As String = "MS_JIGYOSHO"
    Public Const MS_AREA As String = "MS_AREA"
    Public Const MS_EIGYOSHO As String = "MS_EIGYOSHO"
    Public Const TBL_KENSAKU As String = "TBL_KENSAKU"
    Public Const RECORD_KUBUN As String = "RECORD_KUBUN"
    Public Const SEQ As String = "SEQ"
    Public Const PageIndex As String = "PageIndex"
    Public Const BackURL As String = "BackURL"
    Public Const DbError As String = "DbError"
    Public Const LoginID As String = "LoginID"
End Class
